# action.yml
name: AI Reviewer
description: Comment from AI

# GitHub Marketplace - Branding
branding:
  icon: "terminal"
  color: "black"

# Input parameters
inputs:
  GOOGLE_API_KEY:
    description: "Google AI Studio API Key"

# Action steps
runs:
  using: "composite"
  steps:
    - name: Get PR diff and run AI review
      id: ai-review
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        node dist/index.js
      env:
        GOOGLE_API_KEY: ${{ inputs.GOOGLE_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Comment on PR
      if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      shell: bash
      run: |
        REVIEW_CONTENT=$(cat ${GITHUB_ACTION_PATH}/ai_review.txt)
        gh pr comment ${{ env.PR_NUMBER }} --repo $GITHUB_REPOSITORY --body "## AI Review Feedback:

        $REVIEW_CONTENT"
      env:
        GITHUB_TOKEN: ${{ github.token }}
